<a href="https://colab.research.google.com/github/hellloooooo/jjjjjjjj/blob/main/lab_1_Trokhimets_4_8_var30.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Трохимець М.В. ФІТ 4-8 Варіант 9(30)

In [ ]:
import numpy as np

Створіть одновимірний масив (вектор) з числами Фібоначчі, де кожне число дорівнює сумі двох попередніх, та виведіть його значення.


In [ ]:
def fibonacci_arr(n):
    fib_arr = np.zeros(n, dtype=int)
    fib_arr[0] = 0
    if n > 1:
        fib_arr[1] = 1
        for i in range(2, n):
            fib_arr[i] = fib_arr[i-1] + fib_arr[i-2]
    return fib_arr

n = 10
fib_arr = fibonacci_arr(n)
print(fib_arr)


[ 0  1  1  2  3  5  8 13 21 34]



2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями експонент n^2 для кожного натурального числа n,
починаючи з 1, та виведіть його значення.

In [ ]:
def matrix(n):
    arr1 = np.arange(1, 10)
    arr1 = arr1 ** 2
    matrix = arr1.reshape(3, 3)

    return matrix

arr1 = matrix(n)
print(arr1)


[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


3 Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від -1 до 1 та виведіть його значення.

In [ ]:
matrix = np.random.rand(3, 3)
matrix = 2 * matrix - 1
print(matrix)

[[-0.61532965  0.75050089 -0.94214962]
 [ 0.02101499  0.03821178  0.00574284]
 [ 0.53014119  0.69676739 -0.81953085]]


4 Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть середнє геометричне всіх елементів.

In [ ]:
matrix = np.random.rand(3, 3)
product = 1
n = 0

for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        product *= matrix[i, j]
        n += 1

geometric_mean = product ** (1 / n)

print("Matrix:\n", matrix)
print("\nGeometric Mean:\n", geometric_mean)


Matrix:
 [[0.88876706 0.84178867 0.43618927]
 [0.96045431 0.41123786 0.92168165]
 [0.87506537 0.80563469 0.71257911]]

Geometric Mean:
 0.7311070003618925


5 Створіть два одновимірних масиви розміром 6, заповніть їх випадковими дійсними
числами від -5 до 5 та виконайте на них поелементні операції додавання, віднімання
та множення.

In [ ]:
arr1 = np.random.rand(6) * 10 - 5
arr2 = np.random.rand(6) * 10 - 5

sum_result = arr1 + arr2
difference_result = arr1 - arr2
product_result = arr1 * arr2

print("arr1 =", arr1)
print("\narr2 =", arr2)
print("\nSum of elements =", sum_result)
print("\nDifference of elements =", difference_result)
print("\nProduct of elements =", product_result)

arr1 = [-2.55245185  0.67269015  4.96885735 -3.36065224  2.15344866  1.40574014]

arr2 = [-1.04783069 -0.32174407  3.52385893  1.2394082  -4.77739744 -0.22959531]

Sum of elements = [-3.60028254  0.35094608  8.49271628 -2.12124403 -2.62394878  1.17614483]

Difference of elements = [-1.50462116  0.99443422  1.44499841 -4.60006044  6.9308461   1.63533545]

Product of elements = [  2.67453738  -0.21643406  17.50955235  -4.16521995 -10.28788013
  -0.32275135]


6 Створіть дві матриці 5x5, заповніть їх довільними цілими числами від 1 до 10 та
знайдіть їх добуток.

In [ ]:
matrix1 = np.random.randint(1, 11, (5, 5))
matrix2 = np.random.randint(1, 11, (5, 5))

result = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)
print("\nProduct of Matrix 1 and Matrix 2:\n", result)

Matrix 1:
 [[ 5  5  5  4  9]
 [ 2  3  8  7  4]
 [ 4 10  6  3  4]
 [ 3  9  2  7 10]
 [ 8  8  7  1  2]]

Matrix 2:
 [[ 9  9 10  4  6]
 [ 4  1  8  6  8]
 [ 6  2  5  9  7]
 [ 3  9 10 10  6]
 [ 9  2  7  2  4]]

Product of Matrix 1 and Matrix 2:
 [[188 114 218 153 165]
 [135 108 182 176 150]
 [157  93 208 168 180]
 [186 123 252 174 186]
 [167 107 203 157 175]]


In [ ]:
#7 Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами
# в діапазоні від 1 до 10 та перемножте їх між собою.

matrix1 = np.random.randint(1, 11, (3, 2))
matrix2 = np.random.randint(1, 11, (2, 4))

result = np.dot(matrix1, matrix2)

print("Matrix 1 (3x2):\n", matrix1)
print("\nMatrix 2 (2x4):\n", matrix2)
print("\nProduct of Matrix 1 and Matrix 2 (3x4):\n", result)


Matrix 1 (3x2):
 [[5 8]
 [6 6]
 [2 9]]

Matrix 2 (2x4):
 [[5 1 2 2]
 [6 9 8 5]]

Product of Matrix 1 and Matrix 2 (3x4):
 [[73 77 74 50]
 [66 60 60 42]
 [64 83 76 49]]


8 Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.

In [ ]:
matrix = np.random.randint(1, 16, (2, 2))

inverse_matrix = np.linalg.inv(matrix)

print("Original Matrix (2x2):\n", matrix)
print("\nInverse Matrix (2x2):\n", inverse_matrix)


Original Matrix (2x2):
 [[ 7 12]
 [11 12]]

Inverse Matrix (2x2):
 [[-0.25        0.25      ]
 [ 0.22916667 -0.14583333]]


9 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 7 до 15 та транспонуйте її.

In [ ]:
matrix = np.random.randint(7, 16, (3, 3))

transposed_matrix = np.transpose(matrix)

print("Original Matrix (3x3):\n", matrix)
print("\nTransposed Matrix (3x3):\n", transposed_matrix)


Original Matrix (3x3):
 [[15  7 10]
 [ 7 14 10]
 [ 9  7 10]]

Transposed Matrix (3x3):
 [[15  7  9]
 [ 7 14  7]
 [10 10 10]]


In [ ]:
#10 Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1,
# а вектор - випадковими цілими числами в діапазоні від 1 до 10 і знайдіть добуток матриці на вектор.

matrix = np.random.rand(3, 4)
vector = np.random.randint(1, 11, (4, 1))

result = np.dot(matrix, vector)

print("Matrix (3x4):\n", matrix)
print("\nVector (4x1):\n", vector)
print("\nProduct of Matrix and Vector:\n", result)


Matrix (3x4):
 [[0.43425262 0.84129623 0.98612111 0.09144912]
 [0.59412339 0.36890735 0.23145966 0.1867864 ]
 [0.71356952 0.24807962 0.12261058 0.47188728]]

Vector (4x1):
 [[8]
 [5]
 [3]
 [8]]

Product of Matrix and Vector:
 [[11.37045849]
 [ 8.78619404]
 [11.0918843 ]]


In [ ]:
#11 Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1,
# а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

matrix = np.random.rand(2, 3)
vector = np.random.randint(1, 11, (3, 1))

result = np.dot(matrix, vector)

print("Matrix (2x3):\n", matrix)
print("\nVector (3x1):\n", vector)
print("\nProduct of Matrix and Vector:\n", result)


Matrix (2x3):
 [[0.26766559 0.3149049  0.92851292]
 [0.90389669 0.62644391 0.43286215]]

Vector (3x1):
 [[7]
 [2]
 [7]]

Product of Matrix and Vector:
 [[ 9.00305931]
 [10.61019966]]


In [ ]:
#12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 10 та знайдіть суму всіх елементів обох матриць.

matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

total_sum = np.sum(matrix1) + np.sum(matrix2)

print("Matrix 1 (2x2):\n", matrix1)
print("\nMatrix 2 (2x2):\n", matrix2)
print("\nSum of all elements in both matrices:\n", total_sum)


Matrix 1 (2x2):
 [[2 4]
 [9 2]]

Matrix 2 (2x2):
 [[2 6]
 [2 4]]

Sum of all elements in both matrices:
 31


In [ ]:
#13 Створіть дві матриці розміром 10x10, заповніть їх випадковими дійсними числами в
# діапазоні від -2 до 2 та знайдіть їх добуток.

matrix1 = np.random.uniform(-2, 2, (10, 10))
matrix2 = np.random.uniform(-2, 2, (10, 10))

product_matrix = np.dot(matrix1, matrix2)

print("Matrix 1 (10x10):\n", matrix1)
print("\nMatrix 2 (10x10):\n", matrix2)
print("\nProduct of Matrix 1 and Matrix 2 (10x10):\n", product_matrix)


Matrix 1 (10x10):
 [[-1.78769152 -1.43107219 -1.31421884 -0.99900764  0.21155321  1.68559676
  -1.61546899 -1.3088886   0.18053471 -0.00527901]
 [ 1.05057365  1.29492788  0.7338354  -0.8792781   0.24302256 -1.01249467
  -0.88802994  0.34281908  1.9462205   1.86297681]
 [ 1.94374879 -0.23905057 -0.92742669  1.47085822  1.9532612   0.07514692
  -1.24201361  0.95615302  0.87974832  1.67305239]
 [ 0.31750577  0.73213911 -1.41187532  0.75907793  1.02298588 -0.35607179
  -1.55323257  1.00593033  0.03387996  1.82199674]
 [ 1.06587027 -0.50003053  0.2184921  -0.90673045 -1.69617281 -1.48311966
  -1.5361777  -0.67378215 -0.69767551 -1.65873444]
 [ 1.87334467  0.19142634 -1.32207819  0.48325894 -0.00298225 -1.45065098
  -1.01663837  1.5152076  -1.58882058  0.81227443]
 [ 1.9693994   0.65086462  0.93790558  0.43846477 -0.34145119 -1.2079757
  -0.07296776 -1.45900143 -0.54968625 -1.37958537]
 [-1.73233446  1.58486542  0.94307984  1.45599634  0.97355857  1.85752549
   1.20345622 -1.06551007 -1.1902

In [ ]:
#14 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
# діапазоні від -1 до 1 та знайдіть середнє арифметичне значення елементів матриці.

matrix = np.random.uniform(-1, 1, (3, 3))

average_value = np.mean(matrix)

print("Matrix (3x3):\n", matrix)
print("\nAverage value of the elements in the matrix:\n", average_value)


Matrix (3x3):
 [[ 0.93112334  0.18101817 -0.40778477]
 [ 0.10581223  0.39124862 -0.25419072]
 [-0.18830751 -0.93761729 -0.24603911]]

Average value of the elements in the matrix:
 -0.04719300416126843


In [ ]:
#15 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик,
# що містить суму квадратів елементів кожного рядка матриці

matrix = np.random.uniform(0, 1, (3, 3))

sum_of_squares = np.sum(matrix**2, axis=1)
column_vector = sum_of_squares[:, np.newaxis]

print("Matrix (3x3):\n", matrix)
print("\nColumn vector with sum of squares of each row:\n", column_vector)


Matrix (3x3):
 [[0.18223557 0.89373544 0.93306512]
 [0.07397922 0.0461654  0.6294525 ]
 [0.32452493 0.64926164 0.39715332]]

Column vector with sum of squares of each row:
 [[1.70258336]
 [0.40381462]
 [0.68458787]]


In [ ]:
# Висновок: виконавши дану лабораторну роботу,я освоїв методи та дії над матрицями.