<a href="https://colab.research.google.com/github/hellloooooo/Machine_learning/blob/main/Trokhimets_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Трохимець М.В. ФІТ 4-8 Варіант 9(30)

In [2]:
import numpy as np

Створіть одновимірний масив (вектор) з числами Фібоначчі, де кожне число дорівнює сумі двох попередніх, та виведіть його значення.


In [3]:
def fibonacci_arr(n):
    fib_arr = np.zeros(n, dtype=int)
    fib_arr[0] = 0
    if n > 1:
        fib_arr[1] = 1
        for i in range(2, n):
            fib_arr[i] = fib_arr[i-1] + fib_arr[i-2]
    return fib_arr

n = 10
fib_arr = fibonacci_arr(n)
print(fib_arr)


[ 0  1  1  2  3  5  8 13 21 34]



2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями експонент n^2 для кожного натурального числа n,
починаючи з 1, та виведіть його значення.

In [4]:
def matrix(n):
    arr1 = np.arange(1, 10)
    arr1 = arr1 ** 2
    matrix = arr1.reshape(3, 3)

    return matrix

arr1 = matrix(n)
print(arr1)


[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


3 Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від -1 до 1 та виведіть його значення.

In [5]:
matrix = np.random.rand(3, 3)
matrix = 2 * matrix - 1
print(matrix)

[[ 0.81441733  0.91174455 -0.53596978]
 [-0.09468171  0.62870493  0.05680681]
 [-0.31182011 -0.17953573 -0.19157305]]


4 Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть середнє геометричне всіх елементів.

In [6]:
matrix = np.random.rand(3, 3)
product = 1
n = 0

for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        product *= matrix[i, j]
        n += 1

geometric_mean = product ** (1 / n)

print("Matrix:\n", matrix)
print("\nGeometric Mean:\n", geometric_mean)


Matrix:
 [[0.55168504 0.14607276 0.64900754]
 [0.2084601  0.49783584 0.20073416]
 [0.83313154 0.41123665 0.28162595]]

Geometric Mean:
 0.36138384594760664


5 Створіть два одновимірних масиви розміром 6, заповніть їх випадковими дійсними
числами від -5 до 5 та виконайте на них поелементні операції додавання, віднімання
та множення.

In [7]:
arr1 = np.random.rand(6) * 10 - 5
arr2 = np.random.rand(6) * 10 - 5

sum_result = arr1 + arr2
difference_result = arr1 - arr2
product_result = arr1 * arr2

print("arr1 =", arr1)
print("\narr2 =", arr2)
print("\nSum of elements =", sum_result)
print("\nDifference of elements =", difference_result)
print("\nProduct of elements =", product_result)

arr1 = [-1.70254418 -3.03547473  4.83323765  4.87986642  1.79106159  4.63524607]

arr2 = [-0.71075502 -2.04662372  0.69943726 -1.64037691 -0.36068829 -0.68045145]

Sum of elements = [-2.4132992  -5.08209845  5.53267491  3.23948951  1.4303733   3.95479462]

Difference of elements = [-0.99178916 -0.98885102  4.13380039  6.52024333  2.15174988  5.31569752]

Product of elements = [ 1.21009182  6.21247457  3.3805465  -8.00482021 -0.64601494 -3.15405991]


6 Створіть дві матриці 5x5, заповніть їх довільними цілими числами від 1 до 10 та
знайдіть їх добуток.

In [8]:
matrix1 = np.random.randint(1, 11, (5, 5))
matrix2 = np.random.randint(1, 11, (5, 5))

result = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)
print("\nProduct of Matrix 1 and Matrix 2:\n", result)

Matrix 1:
 [[ 6  8  4  2  6]
 [ 8  6  5  7  2]
 [ 6  6  8  8  6]
 [ 4  3 10  8  4]
 [ 5  5  6  9  7]]

Matrix 2:
 [[ 5  5  1  6  7]
 [ 9  4  7  7  6]
 [ 8  8  7  7 10]
 [ 1 10  8  9  9]
 [ 5  8  6  7  1]]

Product of Matrix 1 and Matrix 2:
 [[166 162 142 180 154]
 [151 190 153 202 207]
 [186 246 204 248 236]
 [155 224 183 215 222]
 [162 239 196 237 213]]


In [9]:
#7 Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами
# в діапазоні від 1 до 10 та перемножте їх між собою.

matrix1 = np.random.randint(1, 11, (3, 2))
matrix2 = np.random.randint(1, 11, (2, 4))

result = np.dot(matrix1, matrix2)

print("Matrix 1 (3x2):\n", matrix1)
print("\nMatrix 2 (2x4):\n", matrix2)
print("\nProduct of Matrix 1 and Matrix 2 (3x4):\n", result)


Matrix 1 (3x2):
 [[ 5  7]
 [ 2  2]
 [10  4]]

Matrix 2 (2x4):
 [[8 8 5 3]
 [2 7 3 6]]

Product of Matrix 1 and Matrix 2 (3x4):
 [[ 54  89  46  57]
 [ 20  30  16  18]
 [ 88 108  62  54]]


8 Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.

In [10]:
matrix = np.random.randint(1, 16, (2, 2))

inverse_matrix = np.linalg.inv(matrix)

print("Original Matrix (2x2):\n", matrix)
print("\nInverse Matrix (2x2):\n", inverse_matrix)


Original Matrix (2x2):
 [[14  9]
 [ 9  1]]

Inverse Matrix (2x2):
 [[-0.01492537  0.13432836]
 [ 0.13432836 -0.20895522]]


9 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 7 до 15 та транспонуйте її.

In [11]:
matrix = np.random.randint(7, 16, (3, 3))

transposed_matrix = np.transpose(matrix)

print("Original Matrix (3x3):\n", matrix)
print("\nTransposed Matrix (3x3):\n", transposed_matrix)


Original Matrix (3x3):
 [[10  7 11]
 [11  8  9]
 [14 10  7]]

Transposed Matrix (3x3):
 [[10 11 14]
 [ 7  8 10]
 [11  9  7]]


In [12]:
#10 Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1,
# а вектор - випадковими цілими числами в діапазоні від 1 до 10 і знайдіть добуток матриці на вектор.

matrix = np.random.rand(3, 4)
vector = np.random.randint(1, 11, (4, 1))

result = np.dot(matrix, vector)

print("Matrix (3x4):\n", matrix)
print("\nVector (4x1):\n", vector)
print("\nProduct of Matrix and Vector:\n", result)


Matrix (3x4):
 [[0.94157492 0.97968592 0.24840885 0.16443445]
 [0.90774552 0.90678436 0.36447322 0.51223884]
 [0.57085372 0.11747525 0.29394658 0.78635881]]

Vector (4x1):
 [[3]
 [6]
 [9]
 [4]]

Product of Matrix and Vector:
 [[11.5962577 ]
 [13.49315702]
 [ 8.20836713]]


In [13]:
#11 Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1,
# а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

matrix = np.random.rand(2, 3)
vector = np.random.randint(1, 11, (3, 1))

result = np.dot(matrix, vector)

print("Matrix (2x3):\n", matrix)
print("\nVector (3x1):\n", vector)
print("\nProduct of Matrix and Vector:\n", result)


Matrix (2x3):
 [[0.81220881 0.76882025 0.69442836]
 [0.63343066 0.3236342  0.85062318]]

Vector (3x1):
 [[9]
 [7]
 [4]]

Product of Matrix and Vector:
 [[15.46933445]
 [11.3688081 ]]


In [14]:
#12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 10 та знайдіть суму всіх елементів обох матриць.

matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

total_sum = np.sum(matrix1) + np.sum(matrix2)

print("Matrix 1 (2x2):\n", matrix1)
print("\nMatrix 2 (2x2):\n", matrix2)
print("\nSum of all elements in both matrices:\n", total_sum)


Matrix 1 (2x2):
 [[10  2]
 [ 9  4]]

Matrix 2 (2x2):
 [[ 6 10]
 [ 3  2]]

Sum of all elements in both matrices:
 46


In [15]:
#13 Створіть дві матриці розміром 10x10, заповніть їх випадковими дійсними числами в
# діапазоні від -2 до 2 та знайдіть їх добуток.

matrix1 = np.random.uniform(-2, 2, (10, 10))
matrix2 = np.random.uniform(-2, 2, (10, 10))

product_matrix = np.dot(matrix1, matrix2)

print("Matrix 1 (10x10):\n", matrix1)
print("\nMatrix 2 (10x10):\n", matrix2)
print("\nProduct of Matrix 1 and Matrix 2 (10x10):\n", product_matrix)


Matrix 1 (10x10):
 [[-1.70498177  0.63627161  1.13929913  1.33056735  1.00792789  0.91933787
   1.42793597  0.97042424  1.37907707  0.52715496]
 [ 0.41134434 -1.46803688 -0.72936732  1.18832348  0.39568931  0.80502198
   0.02137957  1.2155874   0.70604713 -1.28867605]
 [-0.08892303  1.05682597 -1.22427091 -1.10194408  0.56177515  1.31644039
  -0.84268989 -1.44363437  0.12348813  0.50978933]
 [-1.01020293  0.11208092  0.82535295 -1.32653622  0.20438807  0.57901996
  -0.5887137   1.36994633 -0.58513008  1.41280264]
 [-1.16293353  1.77955857  1.97673667  1.2514723  -1.0839764   0.53853618
  -0.46649375  0.60552449  0.62324165  0.50279925]
 [-1.70053564  0.48422222  0.43532645 -0.68965416 -1.305002    0.39534028
   0.77439998  1.5431796   1.40113597  1.35593509]
 [-0.76780481  1.79047896 -0.3311642   0.28451471 -1.63349189  0.25139458
   1.0706887   0.30036142 -1.37534609 -0.67290452]
 [ 0.23287335 -1.76880118  0.65538125 -0.33361214 -0.32104165 -0.46130752
  -1.23091352  0.41231917 -1.792

In [16]:
#14 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
# діапазоні від -1 до 1 та знайдіть середнє арифметичне значення елементів матриці.

matrix = np.random.uniform(-1, 1, (3, 3))

average_value = np.mean(matrix)

print("Matrix (3x3):\n", matrix)
print("\nAverage value of the elements in the matrix:\n", average_value)


Matrix (3x3):
 [[-0.02631186  0.79077519 -0.28183089]
 [-0.22091835  0.50150578  0.4616265 ]
 [-0.76181112  0.64434366  0.65392462]]

Average value of the elements in the matrix:
 0.1957003942420029


In [17]:
#15 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик,
# що містить суму квадратів елементів кожного рядка матриці

matrix = np.random.uniform(0, 1, (3, 3))

sum_of_squares = np.sum(matrix**2, axis=1)
column_vector = sum_of_squares[:, np.newaxis]

print("Matrix (3x3):\n", matrix)
print("\nColumn vector with sum of squares of each row:\n", column_vector)


Matrix (3x3):
 [[0.22522298 0.96818667 0.51751305]
 [0.17562963 0.77579897 0.45100008]
 [0.14524221 0.74217851 0.82815767]]

Column vector with sum of squares of each row:
 [[1.25593057]
 [0.83611088]
 [1.25776936]]


In [18]:
# Висновок: виконавши дану лабораторну роботу,я освоїв методи та дії над матрицями.